name: Sync writeups

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout website repo
      uses: actions/checkout@v4
      with:
        repository: DOMBUSTERS/dombusters.github.io
        token: ${{ secrets.WRITEUPS_PAT }}
        path: website

    - name: Checkout writeups repo
      uses: actions/checkout@v4
      with:
        repository: DOMBUSTERS/writeups
        token: ${{ secrets.WRITEUPS_PAT }}
        path: writeups

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Update Python
      run: |
        python -m pip install --upgrade pip

    - name: Run Formatting
      run: |
        cd writeups
        python script.py
        cd ..

    - name: Copy all markdown files
      run: |
        mkdir -p website/src/content/blog
        ls
        find writeups -name '*md' -exec cp {} website/dombusters.github.io/src/content/blog \;

    - name: Copy all assets
      run: |
        mkdir -p website/src/assets/dom-images
        find writeups -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.gif" -o -iname "*.bmp" \) -exec cp {} website/dombusters.github.io/src/assets/dom-images \;
        ls writeups
        ls website

    - name: Commit and push changes
      run: |
        cd website
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Sync writeups and assets"
        git push
